2015-04-19 16:50:26,816 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 16:50:27,072 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 16:50:27,146 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 16:50:27,321 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 16:50:27,394 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 16:50:27,418 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 16:50:27,446 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 16:50:27,472 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 16:50:27,482 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 16:57:54,371 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 16:57:54,407 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 16:57:54,469 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 16:57:54,476 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 16:57:54,517 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 16:57:54,540 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 16:57:54,552 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 16:57:54,562 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 16:57:54,569 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 17:38:56,021 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 17:38:56,026 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 17:38:56,034 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 17:38:56,039 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 17:38:56,043 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 17:38:56,048 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 17:38:56,048 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 17:38:56,050 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 17:38:56,054 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-19 19:04:33 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:47136)
[2015-04-19 19:04:33 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:47128)
[2015-04-19 19:04:33 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:47129)
[2015-04-19 19:04:33 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:47130)
[2015-04-19 19:04:33 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:47131)
[2015-04-19 19:04:33 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:47132)
[2015-04-19 19:04:33 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:47133)
[2015-04-19 19:04:33 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:47134)
[2015-04-19 19:04:33 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:47135)
2015-04-19 19:04:35,163 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 19:04:35,182 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 19:04:35,190 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 19:04:35,207 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 19:04:35,283 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 19:04:35,284 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 19:04:35,304 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 19:04:35,317 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 19:04:35,330 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-19 19:52:44,823 DB error: Unique user not found.
2015-04-19 19:52:44,824 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-19 21:04:54,478 DB error: Unique user not found.
2015-04-19 21:04:54,479 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-19 21:07:19,513 DB error: Unique user not found.
2015-04-19 21:07:19,513 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
[2015-04-20 02:26:25 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:47213)
[2015-04-20 02:26:25 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:47214)
[2015-04-20 02:26:25 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:47215)
[2015-04-20 02:26:25 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:47216)
[2015-04-20 02:26:25 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:47217)
[2015-04-20 02:26:25 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:47218)
[2015-04-20 02:26:25 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:47219)
[2015-04-20 02:26:25 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:47220)
[2015-04-20 02:26:25 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:47221)
2015-04-20 02:26:26,959 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 02:26:26,978 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 02:26:26,981 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 02:26:26,986 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 02:26:26,990 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 02:26:26,999 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 02:26:27,002 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 02:26:27,003 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 02:26:27,007 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-20 10:25:58 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48426)
[2015-04-20 10:25:58 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48428)
[2015-04-20 10:25:58 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48429)
[2015-04-20 10:25:58 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48430)
[2015-04-20 10:25:58 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48432)
[2015-04-20 10:25:58 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48433)
[2015-04-20 10:25:58 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48434)
[2015-04-20 10:25:58 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48435)
[2015-04-20 10:25:58 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48436)
2015-04-20 10:26:00,307 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 10:26:00,472 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 10:26:00,809 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 10:26:00,884 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 10:26:01,008 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 10:26:01,028 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 10:26:01,037 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 10:26:01,046 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 10:26:01,048 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-20 12:04:43 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48449)
[2015-04-20 12:04:43 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48455)
[2015-04-20 12:04:43 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48456)
[2015-04-20 12:04:43 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48439)
[2015-04-20 12:04:43 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48440)
[2015-04-20 12:04:43 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48441)
[2015-04-20 12:04:43 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48442)
[2015-04-20 12:04:43 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48443)
[2015-04-20 12:04:43 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48444)
2015-04-20 12:04:45,162 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 12:04:45,180 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 12:04:45,193 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 12:04:45,202 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 12:04:45,207 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 12:04:45,212 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 12:04:45,217 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 12:04:45,228 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 12:04:45,229 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-20 14:20:47 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48588)
[2015-04-20 14:20:47 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48589)
[2015-04-20 14:20:47 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48590)
[2015-04-20 14:20:47 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48591)
[2015-04-20 14:20:47 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48592)
[2015-04-20 14:20:47 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48593)
[2015-04-20 14:20:47 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48594)
[2015-04-20 14:20:47 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48595)
[2015-04-20 14:20:47 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48596)
2015-04-20 14:20:49,578 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 14:20:49,619 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 14:20:49,614 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 14:20:49,640 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 14:20:49,649 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 14:20:49,674 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 14:20:49,716 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 14:20:49,721 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 14:20:49,725 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-20 15:53:59 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48906)
[2015-04-20 15:53:59 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48907)
[2015-04-20 15:53:59 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48908)
[2015-04-20 15:53:59 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48909)
[2015-04-20 15:53:59 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48910)
[2015-04-20 15:53:59 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48911)
[2015-04-20 15:53:59 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48912)
[2015-04-20 15:53:59 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48913)
[2015-04-20 15:53:59 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48914)
2015-04-20 15:54:01,137 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 15:54:01,151 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 15:54:01,159 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 15:54:01,174 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 15:54:01,183 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 15:54:01,187 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 15:54:01,193 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 15:54:01,202 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 15:54:01,215 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-20 19:32:55 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48938)
[2015-04-20 19:32:55 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48939)
[2015-04-20 19:32:55 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48940)
[2015-04-20 19:32:55 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48941)
[2015-04-20 19:32:55 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48942)
[2015-04-20 19:32:55 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48943)
[2015-04-20 19:32:55 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48944)
[2015-04-20 19:32:55 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48945)
[2015-04-20 19:32:55 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48946)
2015-04-20 19:32:56,595 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 19:32:56,621 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 19:32:56,635 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 19:32:56,660 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 19:32:56,663 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 19:32:56,700 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 19:32:56,721 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 19:32:56,722 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 19:32:56,734 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-20 20:17:11 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48974)
[2015-04-20 20:17:11 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48975)
[2015-04-20 20:17:11 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48976)
[2015-04-20 20:17:11 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48977)
[2015-04-20 20:17:11 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48978)
[2015-04-20 20:17:11 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48979)
[2015-04-20 20:17:11 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48980)
[2015-04-20 20:17:11 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48981)
[2015-04-20 20:17:11 -0700] [46948] [CRITICAL] WORKER TIMEOUT (pid:48982)
2015-04-20 20:17:13,346 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 20:17:13,376 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 20:17:13,396 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 20:17:13,420 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 20:17:13,460 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 20:17:13,463 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 20:17:13,482 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 20:17:13,489 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-20 20:17:13,501 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-22 22:02:45,840 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-22 22:02:46,227 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-22 22:02:46,327 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-22 22:02:46,411 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-22 22:02:46,435 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-22 22:02:46,467 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-22 22:02:46,476 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-22 22:02:46,483 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-22 22:02:46,500 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-23 04:21:39 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:5065)
[2015-04-23 04:21:39 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:5066)
[2015-04-23 04:21:39 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:5067)
[2015-04-23 04:21:39 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:5068)
[2015-04-23 04:21:39 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:5069)
[2015-04-23 04:21:39 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:5070)
[2015-04-23 04:21:39 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:5071)
[2015-04-23 04:21:39 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:5072)
[2015-04-23 04:21:39 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:5073)
2015-04-23 04:21:40,966 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 04:21:40,991 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 04:21:41,135 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 04:21:41,179 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 04:21:41,234 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 04:21:41,237 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 04:21:41,249 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 04:21:41,251 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 04:21:41,275 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-23 09:02:21 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6185)
2015-04-23 09:02:22,834 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-23 09:18:04 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6198)
[2015-04-23 09:18:04 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6190)
[2015-04-23 09:18:04 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6191)
[2015-04-23 09:18:04 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6192)
[2015-04-23 09:18:04 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6165)
[2015-04-23 09:18:04 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6166)
[2015-04-23 09:18:04 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6167)
[2015-04-23 09:18:04 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6168)
[2015-04-23 09:18:04 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6169)
2015-04-23 09:18:06,062 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 09:18:06,102 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 09:18:06,105 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 09:18:06,108 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 09:18:06,114 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 09:18:06,121 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 09:18:06,127 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 09:18:06,136 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 09:18:06,151 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-23 09:38:46 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6231)
[2015-04-23 09:38:46 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6228)
[2015-04-23 09:38:46 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6230)
[2015-04-23 09:38:46 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6232)
[2015-04-23 09:38:46 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6233)
[2015-04-23 09:38:46 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6234)
[2015-04-23 09:38:46 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6235)
[2015-04-23 09:38:46 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6236)
[2015-04-23 09:38:46 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6229)
2015-04-23 09:38:47,955 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 09:38:47,963 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 09:38:48,001 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 09:38:48,009 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 09:38:48,018 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 09:38:48,029 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 09:38:48,039 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 09:38:48,065 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 09:38:48,075 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-23 10:01:38 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6242)
[2015-04-23 10:01:38 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6243)
[2015-04-23 10:01:38 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6244)
[2015-04-23 10:01:38 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6245)
[2015-04-23 10:01:38 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6246)
[2015-04-23 10:01:38 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6247)
[2015-04-23 10:01:38 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6248)
[2015-04-23 10:01:38 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6249)
[2015-04-23 10:01:38 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6250)
2015-04-23 10:01:39,810 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 10:01:39,833 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 10:01:39,862 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 10:01:39,902 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 10:01:39,905 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 10:01:39,972 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 10:01:39,978 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 10:01:40,004 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 10:01:40,020 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-23 11:27:40 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6309)
[2015-04-23 11:27:40 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6310)
[2015-04-23 11:27:40 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6311)
[2015-04-23 11:27:40 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6312)
[2015-04-23 11:27:40 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6313)
[2015-04-23 11:27:40 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6314)
[2015-04-23 11:27:40 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6315)
[2015-04-23 11:27:40 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6316)
[2015-04-23 11:27:40 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6317)
2015-04-23 11:27:42,314 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 11:27:42,319 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 11:27:42,322 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 11:27:42,336 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 11:27:42,343 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 11:27:42,366 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 11:27:42,405 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 11:27:42,418 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 11:27:42,419 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-23 13:30:18 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6612)
[2015-04-23 13:30:18 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6613)
[2015-04-23 13:30:18 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6614)
[2015-04-23 13:30:18 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6615)
[2015-04-23 13:30:18 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6616)
[2015-04-23 13:30:18 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6617)
[2015-04-23 13:30:18 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6618)
[2015-04-23 13:30:18 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6619)
[2015-04-23 13:30:18 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6620)
2015-04-23 13:30:19,918 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 13:30:19,992 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 13:30:20,024 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 13:30:20,176 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 13:30:20,234 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 13:30:20,254 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 13:30:20,265 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 13:30:20,300 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 13:30:20,317 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-23 16:12:34 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6691)
[2015-04-23 16:12:34 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6692)
[2015-04-23 16:12:34 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6693)
[2015-04-23 16:12:34 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6694)
[2015-04-23 16:12:34 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6695)
[2015-04-23 16:12:34 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6696)
[2015-04-23 16:12:34 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6697)
[2015-04-23 16:12:34 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6698)
[2015-04-23 16:12:34 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6699)
2015-04-23 16:12:34,648 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 16:12:34,662 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 16:12:34,687 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 16:12:34,719 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 16:12:34,752 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 16:12:34,784 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 16:12:34,808 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 16:12:34,821 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 16:12:34,824 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-23 18:23:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6816)
[2015-04-23 18:23:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6817)
[2015-04-23 18:23:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6818)
[2015-04-23 18:23:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6819)
[2015-04-23 18:23:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6820)
[2015-04-23 18:23:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6821)
[2015-04-23 18:23:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6822)
[2015-04-23 18:23:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6823)
[2015-04-23 18:23:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6824)
2015-04-23 18:23:44,775 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:23:44,784 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:23:45,663 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:23:45,717 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:23:45,787 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:23:45,805 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:23:45,825 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:23:45,848 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:23:45,866 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-23 18:44:33 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6924)
[2015-04-23 18:44:33 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6925)
[2015-04-23 18:44:33 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6927)
[2015-04-23 18:44:33 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6928)
[2015-04-23 18:44:33 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6929)
[2015-04-23 18:44:33 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6930)
[2015-04-23 18:44:33 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6931)
[2015-04-23 18:44:33 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6932)
[2015-04-23 18:44:33 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:6933)
2015-04-23 18:44:34,608 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:44:34,614 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:44:34,626 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:44:34,632 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:44:34,665 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:44:34,713 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:44:34,729 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:44:34,801 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:44:34,835 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:49:18,515 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:49:18,503 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:49:18,518 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:49:18,524 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:49:18,536 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:49:18,538 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:49:18,554 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:49:18,560 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 18:49:18,564 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 20:21:30,819 Exception on /s [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/psiturk/experiment.py", line 665, in regularpage
    return render_template(pagename)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Library/Python/2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: s
2015-04-23 20:22:14,282 Exception on /s [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/psiturk/experiment.py", line 665, in regularpage
    return render_template(pagename)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Library/Python/2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: s
2015-04-23 20:23:17,462 Exception on /s [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/psiturk/experiment.py", line 665, in regularpage
    return render_template(pagename)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Library/Python/2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: s
2015-04-23 20:23:17,457 Exception on /sync/debugJW25EK:debugDZ6NVT [PUT]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/psiturk/experiment.py", line 522, in update
    db_session.commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 396, in commit
    t[1].commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1560, in commit
    self._do_commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1591, in _do_commit
    self.connection._commit_impl()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 690, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1332, in _handle_dbapi_exception
    exc_info
  File "/Library/Python/2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 688, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 415, in do_commit
    dbapi_connection.commit()
OperationalError: (sqlite3.OperationalError) disk I/O error
2015-04-23 20:23:17,466 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-23 20:23:51,034 DB error: Unique user not found.
2015-04-23 20:23:51,035 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-23 20:23:51,036 Exception on /s [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/psiturk/experiment.py", line 665, in regularpage
    return render_template(pagename)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Library/Python/2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: s
2015-04-23 20:24:31,782 DB error: Unique user not found.
2015-04-23 20:24:31,782 Exception on /s [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/psiturk/experiment.py", line 665, in regularpage
    return render_template(pagename)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Library/Python/2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: s
2015-04-23 20:24:31,782 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-23 20:26:15,518 Exception on /s [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/psiturk/experiment.py", line 665, in regularpage
    return render_template(pagename)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Library/Python/2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: s
2015-04-23 20:26:34,015 DB error: Unique user not found.
2015-04-23 20:26:34,017 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-23 20:26:34,028 Exception on /s [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/psiturk/experiment.py", line 665, in regularpage
    return render_template(pagename)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Library/Python/2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: s
[2015-04-23 21:05:19 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:7148)
[2015-04-23 21:05:19 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:7149)
[2015-04-23 21:05:19 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:7150)
[2015-04-23 21:05:19 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:7151)
[2015-04-23 21:05:19 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:7152)
[2015-04-23 21:05:19 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:7153)
[2015-04-23 21:05:19 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:7154)
[2015-04-23 21:05:19 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:7155)
[2015-04-23 21:05:19 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:7156)
2015-04-23 21:05:21,873 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:05:21,879 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:05:21,912 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:05:21,918 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:05:21,925 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:05:21,930 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:05:21,938 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:05:21,939 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:05:21,940 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-23 21:10:04 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8249)
[2015-04-23 21:10:04 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8241)
[2015-04-23 21:10:04 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8242)
[2015-04-23 21:10:04 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8243)
[2015-04-23 21:10:04 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8245)
[2015-04-23 21:10:04 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8246)
[2015-04-23 21:10:04 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8247)
[2015-04-23 21:10:04 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8248)
[2015-04-23 21:10:04 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8244)
2015-04-23 21:10:06,071 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:10:06,075 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:10:06,128 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:10:06,138 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:10:06,142 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:10:06,150 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:10:06,190 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:10:06,201 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:10:06,211 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-23 21:18:41 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8285)
[2015-04-23 21:18:41 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8286)
[2015-04-23 21:18:41 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8287)
[2015-04-23 21:18:41 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8288)
[2015-04-23 21:18:41 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8289)
[2015-04-23 21:18:41 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8290)
[2015-04-23 21:18:41 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8291)
[2015-04-23 21:18:41 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8292)
[2015-04-23 21:18:41 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8293)
2015-04-23 21:18:42,955 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:18:42,970 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:18:42,995 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:18:43,009 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:18:43,011 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:18:43,013 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:18:43,053 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:18:43,057 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:18:43,064 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-23 21:25:44 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8320)
[2015-04-23 21:25:44 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8321)
[2015-04-23 21:25:44 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8322)
[2015-04-23 21:25:44 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8323)
[2015-04-23 21:25:44 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8315)
[2015-04-23 21:25:44 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8316)
[2015-04-23 21:25:44 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8317)
[2015-04-23 21:25:44 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8318)
[2015-04-23 21:25:44 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8319)
2015-04-23 21:25:47,419 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:25:47,438 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:25:47,461 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:25:47,461 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:25:47,468 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:25:47,476 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:25:47,484 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:25:47,486 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:25:47,491 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-23 21:31:23 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8396)
[2015-04-23 21:31:23 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8397)
[2015-04-23 21:31:23 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8398)
[2015-04-23 21:31:23 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8399)
[2015-04-23 21:31:23 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8400)
[2015-04-23 21:31:23 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8401)
[2015-04-23 21:31:23 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8402)
[2015-04-23 21:31:23 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8404)
[2015-04-23 21:31:23 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8405)
2015-04-23 21:31:24,925 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:31:24,977 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:31:25,005 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:31:25,013 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:31:25,047 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:31:25,066 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:31:25,073 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:31:25,108 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:31:25,122 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-23 21:35:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8416)
[2015-04-23 21:35:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8417)
[2015-04-23 21:35:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8409)
[2015-04-23 21:35:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8410)
[2015-04-23 21:35:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8411)
[2015-04-23 21:35:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8412)
[2015-04-23 21:35:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8413)
[2015-04-23 21:35:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8414)
[2015-04-23 21:35:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8415)
2015-04-23 21:35:44,632 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:35:44,652 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:35:44,679 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:35:44,685 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:35:44,700 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:35:44,724 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:35:44,747 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:35:44,767 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 21:35:44,793 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-23 22:40:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8431)
[2015-04-23 22:40:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8432)
[2015-04-23 22:40:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8433)
[2015-04-23 22:40:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8434)
[2015-04-23 22:40:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8435)
[2015-04-23 22:40:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8436)
[2015-04-23 22:40:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8437)
[2015-04-23 22:40:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8438)
[2015-04-23 22:40:43 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8439)
2015-04-23 22:40:45,183 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 22:40:45,213 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 22:40:45,230 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 22:40:45,240 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 22:40:45,243 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 22:40:45,264 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 22:40:45,288 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 22:40:45,293 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 22:40:45,294 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-23 23:16:16 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8807)
[2015-04-23 23:16:16 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8809)
[2015-04-23 23:16:16 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8810)
[2015-04-23 23:16:16 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8811)
[2015-04-23 23:16:16 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8812)
[2015-04-23 23:16:16 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8813)
[2015-04-23 23:16:16 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8814)
[2015-04-23 23:16:16 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8815)
[2015-04-23 23:16:16 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8816)
2015-04-23 23:16:18,218 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 23:16:18,226 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 23:16:18,228 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 23:16:18,238 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 23:16:18,239 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 23:16:18,244 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 23:16:18,249 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 23:16:18,250 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 23:16:18,259 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-23 23:36:37 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8842)
[2015-04-23 23:36:37 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8843)
[2015-04-23 23:36:37 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8844)
[2015-04-23 23:36:37 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8845)
[2015-04-23 23:36:37 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8846)
[2015-04-23 23:36:37 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8847)
[2015-04-23 23:36:37 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8848)
[2015-04-23 23:36:37 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8850)
[2015-04-23 23:36:37 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:8851)
2015-04-23 23:36:39,081 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 23:36:39,087 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 23:36:39,090 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 23:36:39,103 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 23:36:39,113 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 23:36:39,118 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 23:36:39,149 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 23:36:39,149 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-23 23:36:39,155 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-24 00:20:21 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9152)
[2015-04-24 00:20:21 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9153)
[2015-04-24 00:20:21 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9144)
[2015-04-24 00:20:21 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9145)
[2015-04-24 00:20:21 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9146)
[2015-04-24 00:20:21 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9147)
[2015-04-24 00:20:21 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9149)
[2015-04-24 00:20:21 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9150)
[2015-04-24 00:20:21 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9151)
2015-04-24 00:20:23,137 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:20:23,142 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:20:23,150 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:20:23,150 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:20:23,254 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:20:23,279 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:20:23,296 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:20:23,326 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:20:23,341 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-24 00:28:39 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9179)
[2015-04-24 00:28:39 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9180)
[2015-04-24 00:28:39 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9181)
[2015-04-24 00:28:39 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9182)
[2015-04-24 00:28:39 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9183)
[2015-04-24 00:28:39 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9184)
[2015-04-24 00:28:39 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9185)
[2015-04-24 00:28:39 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9186)
[2015-04-24 00:28:39 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9187)
2015-04-24 00:28:40,876 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:28:40,896 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:28:40,916 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:28:40,919 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:28:40,921 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:28:40,925 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:28:40,961 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:28:40,961 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:28:40,963 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-24 00:32:07 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9233)
[2015-04-24 00:32:07 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9234)
[2015-04-24 00:32:07 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9235)
[2015-04-24 00:32:07 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9236)
[2015-04-24 00:32:07 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9237)
[2015-04-24 00:32:07 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9238)
[2015-04-24 00:32:07 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9239)
[2015-04-24 00:32:07 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9240)
[2015-04-24 00:32:07 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9241)
2015-04-24 00:32:09,432 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:32:09,433 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:32:09,434 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:32:09,453 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:32:09,469 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:32:09,474 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:32:09,482 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:32:09,485 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:32:09,512 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-24 00:41:31 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9248)
[2015-04-24 00:41:31 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9249)
[2015-04-24 00:41:31 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9250)
[2015-04-24 00:41:31 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9251)
[2015-04-24 00:41:31 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9252)
[2015-04-24 00:41:31 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9253)
[2015-04-24 00:41:31 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9254)
[2015-04-24 00:41:31 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9255)
[2015-04-24 00:41:31 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9247)
2015-04-24 00:41:32,307 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:41:32,322 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:41:32,326 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:41:32,328 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:41:32,341 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:41:32,351 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:41:32,356 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:41:32,365 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:41:32,372 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-24 00:44:55 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9263)
[2015-04-24 00:44:55 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9264)
[2015-04-24 00:44:55 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9265)
[2015-04-24 00:44:55 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9266)
[2015-04-24 00:44:55 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9267)
[2015-04-24 00:44:55 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9268)
[2015-04-24 00:44:55 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9269)
[2015-04-24 00:44:55 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9270)
[2015-04-24 00:44:55 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9271)
2015-04-24 00:44:56,822 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:44:56,832 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:44:56,844 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:44:56,847 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:44:56,862 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:44:56,891 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:44:56,900 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:44:56,907 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 00:44:56,932 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-24 03:45:10 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9280)
[2015-04-24 03:45:10 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9281)
[2015-04-24 03:45:10 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9282)
[2015-04-24 03:45:10 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9283)
[2015-04-24 03:45:10 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9284)
[2015-04-24 03:45:10 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9285)
[2015-04-24 03:45:10 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9277)
[2015-04-24 03:45:10 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9278)
[2015-04-24 03:45:10 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9279)
2015-04-24 03:45:11,574 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 03:45:11,583 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 03:45:11,594 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 03:45:11,693 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 03:45:11,701 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 03:45:11,710 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 03:45:11,718 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 03:45:11,727 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 03:45:11,740 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-24 09:32:55 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9289)
[2015-04-24 09:32:55 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9290)
[2015-04-24 09:32:55 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9291)
[2015-04-24 09:32:55 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9293)
[2015-04-24 09:32:55 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9294)
[2015-04-24 09:32:55 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9295)
[2015-04-24 09:32:55 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9296)
[2015-04-24 09:32:55 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9297)
[2015-04-24 09:32:55 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9299)
2015-04-24 09:32:57,593 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 09:32:57,762 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 09:32:57,887 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 09:32:57,974 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 09:32:58,032 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 09:32:58,043 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 09:32:58,048 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 09:32:58,050 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 09:32:58,055 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-24 10:00:49 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9320)
[2015-04-24 10:00:49 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9321)
[2015-04-24 10:00:49 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9322)
[2015-04-24 10:00:49 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9323)
[2015-04-24 10:00:49 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9324)
[2015-04-24 10:00:49 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9326)
[2015-04-24 10:00:49 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9331)
[2015-04-24 10:00:49 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9333)
[2015-04-24 10:00:49 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9334)
2015-04-24 10:00:51,574 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 10:00:51,832 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 10:00:52,000 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 10:00:52,006 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 10:00:52,044 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 10:00:52,051 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 10:00:52,076 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 10:00:52,086 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 10:00:52,088 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-24 10:29:01 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9360)
[2015-04-24 10:29:01 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9361)
[2015-04-24 10:29:01 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9363)
[2015-04-24 10:29:01 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9364)
[2015-04-24 10:29:01 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9365)
[2015-04-24 10:29:01 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9366)
[2015-04-24 10:29:01 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9367)
[2015-04-24 10:29:01 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9368)
[2015-04-24 10:29:01 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9369)
2015-04-24 10:29:03,735 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 10:29:03,738 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 10:29:03,745 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 10:29:03,753 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 10:29:03,754 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 10:29:03,755 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 10:29:03,762 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 10:29:03,769 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 10:29:03,770 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-24 14:05:00 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9590)
[2015-04-24 14:05:00 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9591)
[2015-04-24 14:05:00 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9592)
[2015-04-24 14:05:00 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9593)
[2015-04-24 14:05:00 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9594)
[2015-04-24 14:05:00 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9595)
[2015-04-24 14:05:00 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9596)
[2015-04-24 14:05:00 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9597)
[2015-04-24 14:05:00 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9598)
2015-04-24 14:05:02,209 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 14:05:02,230 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 14:05:02,241 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 14:05:02,243 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 14:05:02,243 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 14:05:02,252 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 14:05:02,259 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 14:05:02,265 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 14:05:02,267 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-24 14:23:38 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9840)
[2015-04-24 14:23:38 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9841)
[2015-04-24 14:23:38 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9842)
[2015-04-24 14:23:38 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9843)
[2015-04-24 14:23:38 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9844)
[2015-04-24 14:23:38 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9845)
[2015-04-24 14:23:38 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9846)
[2015-04-24 14:23:38 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9847)
[2015-04-24 14:23:38 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9848)
2015-04-24 14:23:40,544 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 14:23:40,568 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 14:23:40,572 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 14:23:40,584 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 14:23:40,588 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 14:23:40,591 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 14:23:40,599 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 14:23:40,609 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 14:23:40,611 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 14:24:59,739 Exception on /sync/debugKTJ4PZ:debugD2ZURH [PUT]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/psiturk/experiment.py", line 522, in update
    db_session.commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 2004, in flush
    self._flush(objects)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 2122, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Library/Python/2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 2086, in _flush
    flush_context.execute()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/persistence.py", line 170, in save_obj
    mapper, table, update)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/persistence.py", line 673, in _emit_update_statements
    execute(statement, multiparams)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1332, in _handle_dbapi_exception
    exc_info
  File "/Library/Python/2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) disk I/O error [SQL: u'UPDATE turkdemo SET datastring=? WHERE turkdemo.uniqueid = ?'] [parameters: ('{"condition":0,"counterbalance":0,"assignmentId":"debugD2ZURH","workerId":"debugKTJ4PZ","hitId":"debug1Q1712","currenttrial":6,"bonus":0,"data":[{"uniqueid":"debugKTJ4PZ:debugD2ZURH","current_trial":0,"dateTime":1429910693717,"trialdata":{"phase":"INSTRUCTIONS","templates":["instructions/subjectdata.html","instructions/instruct-1.html","instructions/instruct-2.html","instructions/instruct-3.html","instructions/instruct-ready.html"],"action":"Begin"}},{"uniqueid":"debugKTJ4PZ:debugD2ZURH","current_trial":1,"dateTime":1429910695051,"trialdata":{"phase":"INSTRUCTIONS","template":"instructions/subjectdata.html","indexOf":0,"action":"NextPage","viewTime":1331}},{"uniqueid":"debugKTJ4PZ:debugD2ZURH","current_trial":2,"dateTime":1429910696186,"trialdata":{"phase":"INSTRUCTIONS","template":"instructions/instruct-1.html","indexOf":1,"action":"NextPage","viewTime":1134}},{"uniqueid":"debugKTJ4PZ:debugD2ZURH","current_trial":3,"dateTime":1429910697698,"trialdata":{"phase":"INSTRUCTIONS","template":"instructions/instruct-2.html","indexOf":2,"action":"NextPage","viewTime":1511}},{"uniqueid":"debugKTJ4PZ:debugD2ZURH","current_trial":4,"dateTime":1429910698704,"trialdata":{"phase":"INSTRUCTIONS","template":"instructions/instruct-3.html","indexOf":3,"action":"NextPage","viewTime":1005}},{"uniqueid":"debugKTJ4PZ:debugD2ZURH","current_trial":5,"dateTime":1429910699715,"trialdata":{"phase":"INSTRUCTIONS","template":"instructions/instruct-ready.html","indexOf":4,"action":"FinishInstructions","viewTime":1010}}],"questiondata":{},"eventdata":[{"eventtype":"initialized","value":null,"timestamp":1429910693627,"interval":0},{"eventtype":"window_resize","value":[991,538],"timestamp":1429910693627,"interval":0}],"useragent":""}', u'debugKTJ4PZ:debugD2ZURH')]
2015-04-24 14:37:24,064 DB error: Unique user not found.
2015-04-24 14:37:24,065 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-24 14:46:34,894 DB error: Unique user not found.
2015-04-24 14:46:34,895 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-24 14:52:36,856 DB error: Unique user not found.
2015-04-24 14:52:36,857 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-24 14:53:56,628 DB error: Unique user not found.
2015-04-24 14:53:56,629 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-24 14:54:18,453 Exception on /sync/debugKTJ4PZ:debugD2ZURH [PUT]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/psiturk/experiment.py", line 522, in update
    db_session.commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 396, in commit
    t[1].commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1560, in commit
    self._do_commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1591, in _do_commit
    self.connection._commit_impl()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 690, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1332, in _handle_dbapi_exception
    exc_info
  File "/Library/Python/2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 688, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 415, in do_commit
    dbapi_connection.commit()
OperationalError: (sqlite3.OperationalError) disk I/O error
2015-04-24 14:54:18,460 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
[2015-04-24 15:53:22 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9984)
[2015-04-24 15:53:22 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9985)
[2015-04-24 15:53:22 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9986)
[2015-04-24 15:53:22 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9987)
[2015-04-24 15:53:22 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9988)
[2015-04-24 15:53:22 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9989)
[2015-04-24 15:53:22 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9990)
[2015-04-24 15:53:22 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9991)
[2015-04-24 15:53:22 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:9992)
2015-04-24 15:53:23,909 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 15:53:23,912 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 15:53:23,932 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 15:53:23,945 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 15:53:23,956 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 15:53:23,958 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 15:53:23,965 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 15:53:23,974 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 15:53:23,979 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-24 15:59:34 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10133)
[2015-04-24 15:59:34 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10134)
[2015-04-24 15:59:34 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10135)
[2015-04-24 15:59:34 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10136)
[2015-04-24 15:59:34 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10137)
[2015-04-24 15:59:34 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10138)
[2015-04-24 15:59:34 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10139)
[2015-04-24 15:59:34 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10140)
[2015-04-24 15:59:34 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10141)
2015-04-24 15:59:37,740 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 15:59:37,741 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 15:59:37,743 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 15:59:37,758 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 15:59:37,773 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 15:59:37,779 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 15:59:37,781 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 15:59:37,797 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 15:59:37,800 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 16:12:13,919 DB error: Unique user not found.
2015-04-24 16:12:13,920 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-24 16:13:25,370 DB error: Unique user not found.
2015-04-24 16:13:25,371 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-24 16:43:52,519 DB error: Unique user not found.
2015-04-24 16:43:52,521 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
[2015-04-24 18:45:46 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10147)
[2015-04-24 18:45:46 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10148)
[2015-04-24 18:45:46 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10149)
[2015-04-24 18:45:46 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10150)
[2015-04-24 18:45:46 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10151)
[2015-04-24 18:45:46 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10152)
[2015-04-24 18:45:46 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10153)
[2015-04-24 18:45:46 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10154)
[2015-04-24 18:45:46 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10155)
2015-04-24 18:45:47,961 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 18:45:47,992 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 18:45:48,048 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 18:45:48,057 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 18:45:48,143 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 18:45:48,197 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 18:45:48,213 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 18:45:48,226 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 18:45:48,233 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-24 19:37:18 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10624)
[2015-04-24 19:37:18 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10625)
[2015-04-24 19:37:18 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10617)
[2015-04-24 19:37:18 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10618)
[2015-04-24 19:37:18 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10619)
[2015-04-24 19:37:18 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10620)
[2015-04-24 19:37:18 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10621)
[2015-04-24 19:37:18 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10622)
[2015-04-24 19:37:18 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10623)
2015-04-24 19:37:20,125 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 19:37:20,136 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 19:37:20,156 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 19:37:20,184 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 19:37:20,186 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 19:37:20,203 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 19:37:20,215 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 19:37:20,223 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 19:37:20,240 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-24 21:50:14 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10835)
[2015-04-24 21:50:14 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10836)
[2015-04-24 21:50:14 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10838)
[2015-04-24 21:50:14 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10839)
[2015-04-24 21:50:14 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10840)
[2015-04-24 21:50:14 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10841)
[2015-04-24 21:50:14 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10842)
[2015-04-24 21:50:14 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10843)
[2015-04-24 21:50:14 -0700] [5061] [CRITICAL] WORKER TIMEOUT (pid:10844)
2015-04-24 21:50:16,456 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 21:50:16,482 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 21:50:16,485 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 21:50:16,499 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 21:50:16,504 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 21:50:16,508 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 21:50:16,514 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 21:50:16,514 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-24 21:50:16,516 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 17:22:01,201 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 17:22:01,436 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 17:22:01,492 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 17:22:01,671 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 17:22:01,704 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 17:22:01,722 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 17:22:01,731 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 17:22:01,742 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 17:22:01,742 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 17:23:38,108 Exception on /exi1stage.html [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/psiturk/experiment.py", line 665, in regularpage
    return render_template(pagename)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Library/Python/2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: exi1stage.html
2015-04-25 17:23:40,294 Exception on /exi1stage.html [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/psiturk/experiment.py", line 665, in regularpage
    return render_template(pagename)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Library/Python/2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: exi1stage.html
2015-04-25 17:23:52,622 Exception on /exi1stage.html [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/psiturk/experiment.py", line 665, in regularpage
    return render_template(pagename)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Library/Python/2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Library/Python/2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: exi1stage.html
2015-04-25 17:24:31,961 DB error: Unique user not found.
2015-04-25 17:24:31,962 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
[2015-04-25 18:52:20 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:4940)
[2015-04-25 18:52:20 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:4941)
[2015-04-25 18:52:20 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:4942)
[2015-04-25 18:52:20 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:4943)
[2015-04-25 18:52:20 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:4944)
[2015-04-25 18:52:20 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:4945)
[2015-04-25 18:52:20 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:4946)
[2015-04-25 18:52:20 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:4947)
[2015-04-25 18:52:20 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:4948)
2015-04-25 18:52:21,813 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 18:52:21,835 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 18:52:21,982 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 18:52:22,352 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 18:52:22,355 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 18:52:22,365 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 18:52:22,388 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 18:52:22,405 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 18:52:22,406 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-25 18:56:10 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5099)
[2015-04-25 18:56:10 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5100)
[2015-04-25 18:56:10 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5102)
[2015-04-25 18:56:10 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5103)
[2015-04-25 18:56:10 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5104)
[2015-04-25 18:56:10 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5105)
[2015-04-25 18:56:10 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5106)
[2015-04-25 18:56:10 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5107)
[2015-04-25 18:56:10 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5108)
2015-04-25 18:56:11,687 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 18:56:11,695 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 18:56:11,703 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 18:56:11,708 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 18:56:11,711 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 18:56:11,720 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 18:56:11,722 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 18:56:11,729 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 18:56:11,733 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 18:56:23,597 Exception on /sync/debugES3N7C:debugQ2DWK5 [PUT]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/psiturk/experiment.py", line 522, in update
    db_session.commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 396, in commit
    t[1].commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1560, in commit
    self._do_commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1591, in _do_commit
    self.connection._commit_impl()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 690, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1332, in _handle_dbapi_exception
    exc_info
  File "/Library/Python/2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 688, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 415, in do_commit
    dbapi_connection.commit()
OperationalError: (sqlite3.OperationalError) disk I/O error
2015-04-25 18:56:23,604 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-25 19:05:47,234 DB error: Unique user not found.
2015-04-25 19:29:24,774 DB error: Unique user not found.
2015-04-25 19:29:24,775 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
[2015-04-25 19:46:45 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5120)
[2015-04-25 19:46:45 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5112)
[2015-04-25 19:46:45 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5114)
[2015-04-25 19:46:45 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5115)
[2015-04-25 19:46:45 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5118)
[2015-04-25 19:46:45 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5119)
2015-04-25 19:46:46,806 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 19:46:46,813 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 19:46:46,822 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 19:46:46,830 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 19:46:46,846 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 19:46:46,851 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-04-25 19:50:07 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5194)
[2015-04-25 19:50:07 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5195)
[2015-04-25 19:50:07 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5196)
[2015-04-25 19:50:07 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5197)
[2015-04-25 19:50:07 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5198)
[2015-04-25 19:50:07 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5199)
[2015-04-25 19:50:07 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5113)
[2015-04-25 19:50:07 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5116)
[2015-04-25 19:50:07 -0700] [4936] [CRITICAL] WORKER TIMEOUT (pid:5117)
2015-04-25 19:50:09,032 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 19:50:09,040 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 19:50:09,041 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 19:50:09,045 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 19:50:09,079 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 19:50:09,096 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 19:50:09,121 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 19:50:09,129 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 19:50:09,143 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:24:02,199 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:24:02,266 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:24:02,507 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:24:02,672 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:24:02,679 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:24:02,682 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:24:02,695 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:24:02,707 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:24:02,711 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:54:18,129 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:54:18,130 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:54:18,494 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:54:18,558 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:54:18,594 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:54:18,623 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:54:18,644 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:54:18,655 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:54:18,657 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:54:39,998 hit_assign_worker_id_not_set_in_mturk (1001) {}
2015-04-25 20:55:29,792 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:55:29,908 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:55:29,939 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:55:30,014 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:55:30,025 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:55:30,099 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:55:30,108 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:55:30,119 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 20:55:30,125 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 21:16:52,573 DB error: Unique user not found.
2015-04-25 21:16:52,574 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-25 22:13:23,278 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 22:13:23,425 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 22:13:23,468 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 22:13:23,552 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 22:13:23,604 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 22:13:23,616 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 22:13:23,621 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 22:13:23,638 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 22:13:23,667 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-04-25 22:14:52,550 DB error: Unique user not found.
2015-04-25 22:14:52,551 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-25 22:34:21,001 Exception on /sync/debugZVJDAO:debug23S74C [PUT]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/psiturk/experiment.py", line 522, in update
    db_session.commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 396, in commit
    t[1].commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1560, in commit
    self._do_commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1591, in _do_commit
    self.connection._commit_impl()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 690, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1332, in _handle_dbapi_exception
    exc_info
  File "/Library/Python/2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 688, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 415, in do_commit
    dbapi_connection.commit()
OperationalError: (sqlite3.OperationalError) disk I/O error
2015-04-25 22:34:21,019 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-25 22:37:03,143 Exception on /sync/debugZVJDAO:debug23S74C [PUT]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/psiturk/experiment.py", line 522, in update
    db_session.commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 396, in commit
    t[1].commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1560, in commit
    self._do_commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1591, in _do_commit
    self.connection._commit_impl()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 690, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1332, in _handle_dbapi_exception
    exc_info
  File "/Library/Python/2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 688, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 415, in do_commit
    dbapi_connection.commit()
OperationalError: (sqlite3.OperationalError) disk I/O error
2015-04-25 22:37:03,147 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-25 22:40:52,711 Exception on /sync/debugZVJDAO:debug23S74C [PUT]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/psiturk/experiment.py", line 522, in update
    db_session.commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 396, in commit
    t[1].commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1560, in commit
    self._do_commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1591, in _do_commit
    self.connection._commit_impl()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 690, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1332, in _handle_dbapi_exception
    exc_info
  File "/Library/Python/2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 688, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 415, in do_commit
    dbapi_connection.commit()
OperationalError: (sqlite3.OperationalError) disk I/O error
2015-04-25 22:40:52,713 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-25 22:57:10,320 DB error: Unique user not found.
2015-04-25 23:01:29,820 DB error: Unique user not found.
2015-04-25 23:01:29,821 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-25 23:02:38,240 DB error: Unique user not found.
2015-04-25 23:02:38,241 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-25 23:03:21,358 DB error: Unique user not found.
2015-04-25 23:03:21,359 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-25 23:04:03,217 Exception on /sync/debugK4DXNH:debugGMH6NA [PUT]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/psiturk/experiment.py", line 522, in update
    db_session.commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 396, in commit
    t[1].commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1560, in commit
    self._do_commit()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1591, in _do_commit
    self.connection._commit_impl()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 690, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1332, in _handle_dbapi_exception
    exc_info
  File "/Library/Python/2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 688, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 415, in do_commit
    dbapi_connection.commit()
OperationalError: (sqlite3.OperationalError) disk I/O error
2015-04-25 23:04:03,219 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-25 23:07:25,433 DB error: Unique user not found.
2015-04-25 23:07:25,434 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-25 23:09:00,350 DB error: Unique user not found.
2015-04-25 23:09:00,351 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-04-25 23:13:49,668 DB error: Unique user not found.
2015-04-25 23:13:49,670 Exception during reset or similar
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
OperationalError: cannot rollback - no transaction is active
2015-05-01 21:31:47,081 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-05-01 21:31:47,186 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-05-01 21:31:47,184 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-05-01 21:31:47,221 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-05-01 21:31:47,302 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-05-01 21:31:47,329 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-05-01 21:31:47,335 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-05-01 21:31:47,348 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-05-01 21:31:47,349 /Library/Python/2.7/site-packages/psiturk/psiturk_js/psiturk.js
